/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DeckgoSlideCountdown {
        "afterSwipe": () => Promise<void>;
        "beforeSwipe": (_enter: boolean, _reveal: boolean) => Promise<boolean>;
        /**
          * The amount of days before your presentations
         */
        "days": number;
        "hideContent": () => Promise<void>;
        /**
          * The amount of hours before your presentations (max. 23)
         */
        "hours": number;
        "lazyLoadContent": () => Promise<void>;
        /**
          * The amount of minutes before your presentations (max. 59)
         */
        "minutes": number;
        "revealContent": () => Promise<void>;
        "seconds": number;
        "start": () => Promise<void>;
        "stop": () => Promise<void>;
        /**
          * A specific date and time until when your presentation will start (format: 2021-08-27T23:25:59.000+02:00)
         */
        "until": string;
    }
}
declare global {
    interface HTMLDeckgoSlideCountdownElement extends Components.DeckgoSlideCountdown, HTMLStencilElement {
    }
    var HTMLDeckgoSlideCountdownElement: {
        prototype: HTMLDeckgoSlideCountdownElement;
        new (): HTMLDeckgoSlideCountdownElement;
    };
    interface HTMLElementTagNameMap {
        "deckgo-slide-countdown": HTMLDeckgoSlideCountdownElement;
    }
}
declare namespace LocalJSX {
    interface DeckgoSlideCountdown {
        /**
          * The amount of days before your presentations
         */
        "days"?: number;
        /**
          * The amount of hours before your presentations (max. 23)
         */
        "hours"?: number;
        /**
          * The amount of minutes before your presentations (max. 59)
         */
        "minutes"?: number;
        "onSlideDidLoad"?: (event: CustomEvent<void>) => void;
        "seconds"?: number;
        /**
          * A specific date and time until when your presentation will start (format: 2021-08-27T23:25:59.000+02:00)
         */
        "until"?: string;
    }
    interface IntrinsicElements {
        "deckgo-slide-countdown": DeckgoSlideCountdown;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "deckgo-slide-countdown": LocalJSX.DeckgoSlideCountdown & JSXBase.HTMLAttributes<HTMLDeckgoSlideCountdownElement>;
        }
    }
}
